require(tm)
TEXTFILE = "./text.txt"
input = readLines(TEXTFILE)
length(input)
df1 <- data.frame(words=input)
cf1 <- Corpus(VectorSource(df1$words))
cf1 <- tm_map(cf1, content_transformer(tolower))
cf1 <- tm_map(cf1, content_transformer(removePunctuation))
cf1 <- tm_map(cf1, content_transformer(removeNumbers))
cf1 <- tm_map(cf1, content_transformer(removeWords), stopwords("english"))
tdm1 <- TermDocumentMatrix(cf1, control=list(stemDocument=TRUE))
as.matrix(tdm1)
m <- inspect(tdm1)
DF <- as.data.frame(m, stringsAsFactors = FALSE)
write.table(DF,"output.txt")